openapi: 3.0.3
info:
  title: Service Account Token API
  description: |-
    **_These APIs are deprecated, use OAuth2 with client_credentials_**
    
    Service Account Token API is an API based on [JSON Web Token (JWT) Profile
      for OAuth 2.0 Client Authentication and Authorization Grants](https://datatracker.ietf.org/doc/html/rfc7523) specification.
      
      Sandbox server: `https://sandbox.api.high-mobility.com`
      
      Production server: `https://api.high-mobility.com`

  contact:
    email: support@high-mobility.com
  version: 1.0.0
externalDocs:
  description: High Mobility's Developer Console
  url: https://www.high-mobility.com
servers:
  - url: https://sandbox.api.high-mobility.com
  - url: https://api.high-mobility.com

paths:
  /v1/auth_tokens:
    post:
      deprecated: true
      tags:
        - Deprecated        
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceAccountTokenRequest'
      summary: ''
      responses:
        '201':
          content:
            application/json:
              schema:        
                $ref: '#/components/schemas/ServiceAccountTokenResponse'
          description: Success
        '401':
          content:
            application/json:
              schema:   
                $ref: '#/components/schemas/AuthTokenUnauthorizedErrors'
          description: When the JWT is invalid or not signed correctly
        '422':
          content:
            application/json:        
              schema:
               $ref: '#/components/schemas/Errors'
          description: Errors
        '500':
          description: Server Errors
      operationId: ApiWeb.ServiceAccountTokenController.create
      description: >-
        Deprecation: This API is deprecated, use OAuth2 with client_credentials
  
  
  /v1/auth_tokens/{auth_token}:
    delete:
      deprecated: true
      tags:
        - Deprecated    
      summary: ''
      parameters:
        - schema:
            type: string
          required: true
          name: auth_token
          in: path
          description: The Auth token to revoke
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccountTokenResponse'
          description: Success
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrors'            
          description: When an invalid ServiceAccountToken is used.
        '404':
          content:
            application/json:        
              schema:
                $ref: '#/components/schemas/Errors'
          description: Success
        '422':
          content:
            application/json:        
              schema:
               $ref: '#/components/schemas/Errors'
          description: Errors
        '500':
          description: Server Errors
      operationId: ApiWeb.ServiceAccountTokenController.delete
      description: Revokes a Service Account API authorization token.

          
      
      
 
components:
  schemas:
    ServiceAccountTokenRequest:
      type: object
      properties:
        assertion:
          type: string
          description: >-
            A JWT Signed with the service account key, read more at
            https://high-mobility.com/learn/documentation/cloud-api/service-account-api/intro/

          
      example:
        assertion: >-
          eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJ2ZXIiOjEsImp0aSI6IjA3M2UxOTM1LTkwZDAtNDE0Mi05MTgzLWE4ZTAxNzNhZDJlNyIsImlzcyI6IjAxMDA4MmNjLTYzZTAtNGRmMy05ZmRhLTAzZThkOWQzN2I1OCIsImlhdCI6IjIwMTYtMTAtMDZUMTc6MDQ6MzQuNDQzNDc5KzAwOjAwIiwiYXVkIjoiaHR0cHM6Ly9hcGkuaGlnaC1tb2JpbGl0eS5jb20vYXBpL3YxIn0.MEQCIG8VHMVGJL_rAaxWEvWMoSMmxNBn9Fl46zcEP9l4fFGNAiBDr9bCzx0MLi0pDBMTg1w9ZAl6VJuxeVIC7c6o8YfxQw
        grant_type: urn:ietf:params:oauth:grant-type:jwt-bearer
          
    UnauthorizedErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Errors'
          example:
            - detail: >
                Missing or invalid authorization header. The token must be
                obtained through the service account API and sent as a header with
                the format "Authorization: Bearer <token>"
              source: Authorization  
    ServiceAccountTokenResponse:
      type: object
      title: ServiceAccountToken
      required:
        - valid_until
        - valid_from
        - auth_token
      properties:
        access_token:
          type: string
        valid_until:
          type: string
          description: When the token expires, formatted in ISO8601
        valid_from:
          type: string
          description: From when the token is valid, formatted in ISO8601
        auth_token:
          type: string
          description: The authorization token
      example:
        token_type: bearer
        expires_in: 300
        access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODgzNzkwMzksImlhdCI6MTY4ODM3ODczOSwiaXNzIjoiaHR0cHM6Ly9zYW5kYm94LmFwaS5oaWdoLW1vYmlsaXR5LmNvbS92MS9hdXRoX3Rva2VucyIsImp0aSI6IjFiY2ZjOTBkLTQ2NTMtNDQyZS05MmE3LWM5N2U2MmMxMDlmYyIsInNlcnZpY2VfYWNjb3VudF9pZCI6IjYxOTZmZTZlLWE0ZTQtNDZjYi1iM2U3LTZiODk5MmFlOGFjOCIsInN1YiI6IjUxYTNmYmQ5LWEwZjUtNDY1Yi1iOTA3LTM5MWQ1YTBmNjM3NiIsInZlciI6MX0.sXYHak_aKTsqMC5ILgfu-PCgWsACbrdHDKjHRFNTm0M
        scope: "fleet:clearance fleet:geofencing vehicle:eligibility-check vehicle:data"

    Errors:
      type: array
      title: Errors
      items:
        $ref: '#/components/schemas/Error'
      description: List of errors
    Error:
      type: object
      title: Error
      required:
        - title
      properties:
        title:
          type: string
          description: Error title
        source:
          type: string
          description: Field that has problem
        detail:
          type: string
          description: Error detail
      description: Error details
      
    AuthTokenUnauthorizedErrors:
      type: object
      title: Errors
      properties:
        errors:
          description: List of errors
          type: array
          items:
            $ref: '#/components/schemas/Error'
          example:
            - detail: >-
                Missing or invalid assertion. It must be a JWT signed with the
                service account key
              source: Authorization
              title: Not authorized
              

