info:
  description: |-
    This endpoint allows you to retrieve static vehicle data through a RESTful interface.

    Authentication: 
     * For fleet flow use [OAuth2](https://docs.high-mobility.com/guides/platform/oauth2-client-credentials/) using `client_credentials` grant type to obtain access token.



    Servers:
    * Production server: `https://api.high-mobility.com`
  title: Static Data API
  version: 1.0.0
openapi: 3.0.3


paths:
  /v1/vehicle-static-data/{vin}:
    get:
      summary: Vehicle Static Data
      parameters:
        - description: Vehicle Identification number
          in: path
          name: vin
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleStaticDataResponse'
              examples:
                successful:
                  value:
                    manufacturer:
                      brand: "Jeep"
                      sub_model: "80th Anniversary Plug-In Hybrid 4WD"
                      type_group_name: "Compass"
                      model: "Compass (M7)(2020->)"
                      sales_description: "Compass 1.3 Plug-In Hybrid (EURO 6d) 80th Annivers"
                      vehicle_main_type_key: "111"
                      vehicle_sub_type_key: "30"
                      vehicle_type_key: "1"
                    equipment:
                      series_equipment:
                        - description: "airbag driver side/passenger side"
                          positions: []
                          manufacturer_id: null
                        - descripion: "navigation package"
                          positions:
                            - description: "driver assistance system: traffic sign detection (TSR)"
                          manufacturer_id: "JPE"
                      special_equipment:
                        - description: "Winter package"
                          positions:
                            - description: "windshield wiper heated"
                          manufacturer_id: AAC                     
          description: successful operation
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleStaticDataResponse401'            
              examples:
                Invalid authorization header:
                  value:
                    errors:
                      - detail: Missing or invalid authorization header
                        title: Not Authorized
                    request_id: 89c6b29a-caca-449d-9a60-e2ca21a60fe3  
                ExpiredToken:
                  value:
                    errors:
                      - detail: Expired token
                        title: Not Authorized
                    request_id: 32c6b29a-caca-449d-9a60-e2ca21a60fe3  
                Invalid JWT Payload:
                  value:
                    errors:
                      - detail: Invalid JWT Payload
                        title: Not Authorized
                    request_id: 32c6b29a-caca-449d-9a60-e2ca21a60fe3
          description: Not Authorized
      security:
        - VehicleStaticDataAuth:
            - vehicle:static-data
      tags:
        - Static Data API
servers:
  - url: https://sandbox.api.high-mobility.com
  - url: https://api.high-mobility.com
  
components:  
  schemas:
    VehicleStaticDataManufacturer:
      properties:
        brand:
          type: string
        sub_model:
          type: string
        type_group_name:
          type: string
        model:
          type: string
        sales_description:
          type: string
        vehicle_main_type_key:
          type: string
        vehicle_sub_type_key:
          type: string
        vehicle_type_key:
          type: string
    VehicleStaticDataEquipment:
      properties:
        series_equipment:
          type: array
          items:
            $ref: '#/components/schemas/VehicleStaticDataEquipmentList'
        special_equipment:
          type: array
          items:
            $ref: '#/components/schemas/VehicleStaticDataEquipmentList'

    VehicleStaticDataEquipmentList:
      properties:
        manufacturer_id:
          type: string
        description:
          type: string
        positions:
          type: array
          items:
            type: string

    VehicleStaticDataResponse:
      properties:
        manufacturer:
          $ref: '#/components/schemas/VehicleStaticDataManufacturer'
        equipment:
          $ref: '#/components/schemas/VehicleStaticDataEquipment'

    VehicleStaticDataResponse401:
      properties:
        errors:
          items:
            properties:
              detail:
                example: Failure when fetching data from OEM
                type: string
              title:
                example: Service Unavailable
                type: string
            type: object
          type: array
        request_id:
          description: The request tracking id. Provide request_id when facing issue
          type: string  
  securitySchemes:
    VehicleStaticDataAuth:
      flows:
        clientCredentials:
          scopes:
            vehicle:static-data: static vehicle data
          tokenUrl: https://api.sandbox.high-mobility.com/v1/access_token
      type: oauth2
