info:
  description: |-
    This endpoint allows you to retrieve static vehicle data through a RESTful interface.

    Authentication: 
     * For fleet flow use [OAuth2](https://docs.high-mobility.com/guides/platform/oauth2-client-credentials/) using `client_credentials` grant type to obtain access token.



    Sandbox server: `https://sandbox.api.high-mobility.com`


    Production server: `https://api.high-mobility.com`
  title: Vehicle Static Data API(Draft)
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/vehicle-static-data/{vin}:
    get:
      summary: Vehicle Static Data
      parameters:
        - description: Vehicle Identification number
          in: path
          name: vin
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
          description: successful operation
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response401'            
              examples:
                Invalid authorization header:
                  value:
                    errors:
                      - detail: Missing or invalid authorization header
                        title: Not Authorized
                    request_id: 89c6b29a-caca-449d-9a60-e2ca21a60fe3  
                ExpiredToken:
                  value:
                    errors:
                      - detail: Expired token
                        title: Not Authorized
                    request_id: 32c6b29a-caca-449d-9a60-e2ca21a60fe3  
                Invalid JWT Payload:
                  value:
                    errors:
                      - detail: Invalid JWT Payload
                        title: Not Authorized
                    request_id: 32c6b29a-caca-449d-9a60-e2ca21a60fe3
          description: Not Authorized
      security:
        - VehicleStaticDataAuth:
            - vehicle:static-data
      tags:
        - Data API
servers:
  - url: https://sandbox.api.high-mobility.com
  - url: https://api.high-mobility.com
  
components:  
  schemas:
    response:
      properties:
        data:
          type: object
    response401:
      properties:
        errors:
          items:
            properties:
              detail:
                example: Failure when fetching data from OEM
                type: string
              title:
                example: Service Unavailable
                type: string
            type: object
          type: array
        request_id:
          description: The request tracking id. Provide request_id when facing issue
          type: string  
  securitySchemes:
    VehicleStaticDataAuth:
      flows:
        clientCredentials:
          scopes:
            vehicle:data: all all configured vehicle data
          tokenUrl: https://api.sandbox.high-mobility.com/v1/access_token
      type: oauth2
