# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Verify Doc Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docs
      run: |
        npx --yes @redocly/cli join introduction.yml hm-oauth-rest-v1.yml  hm-vehicle-data-api-v1.yml hm-vehicle-static-data-api-v1.yml  hm-fleet-clearance-v1.yml hm-eligibility-v1.yml   -o hm-apis.yaml
        npx @redocly/cli build-docs hm-apis.yaml
